### ISSUE TITLE
CreatePickCard error

### ISSUE THREAD

**Issue by MarkFarmiloe** [isaacabraham/monopoly#1]
In Controller.fs, line 67 ends random.Next(0, 15)
It should end random.Next(0, 16)
though I find it counter-intuitive too.

**Comment by isaacabraham** [comment]
Good spot :-) Any chance you could submit a PR for this? If not, no worries.

**Comment by MarkFarmiloe** [comment]
Hi Isaac,

 

I expect I could. Give me a day.

 

I have a question though. 

Is there any way of forcing CreditAccount creation to only be possible via rateAccount, because otherwise it isn’t ENFORCING the business rule, just facilitating it.

I prefer enforcement.

 

Best regards

Mark

**Comment by isaacabraham** [comment]
@MarkFarmiloe thanks. Regarding the bank accounts stuff - can you raise a question for that on the MEAP forum rather than here :-) And the answer is yes you can through use of signature files - it's a bit overkill in my experience, but you can do it.
